### ISSUE TITLE
ami-64385917 not found

### ISSUE THREAD

**Issue by davecarlson** [plesk/wordpress-aws-scaler#13]
When trying to deploy this, AWS says it cannot find the AMI ami-64385917. Is this a private one, and if so, what AMI was it based off ?

**Comment by robdyke** [comment]
@davecarlson You need to set AMI and REGION keys with values found here: [latest Amazon ECS-optimized AMI IDs](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html).

```
AMI 'ami-ba346ec9'
REGION 'eu-west-1'
```
